# Generated by Django 5.0.2 on 2024-04-07 08:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('manufacturer', models.CharField(choices=[('1stPlayer', '1stPlayer'), ('AeroCool', 'AeroCool'), ('Antec', 'Antec'), ('Asus', 'Asus'), ('be quiet!', 'be quiet!'), ('BitFenix', 'BitFenix'), ('Chieftec', 'Chieftec'), ('CoolerMaster', 'CoolerMaster'), ('Corsair', 'Corsair'), ('Cougar Gaming', 'Cougar Gaming'), ('DeepCool', 'DeepCool'), ('Endorfy', 'Endorfy'), ('Fractal Design', 'Fractal Design'), ('FSP', 'FSP'), ('Fury', 'Fury'), ('Gamdias', 'Gamdias'), ('Genesis', 'Genesis'), ('Genesys Group', 'Genesys Group'), ('Gigabyte', 'Gigabyte'), ('HYTE', 'HYTE'), ('In Win', 'In Win'), ('Inter-Tech', 'Inter-Tech'), ('Jonsbo', 'Jonsbo'), ('Kolink', 'Kolink'), ('LC Power', 'LC Power'), ('Lian Li', 'Lian Li'), ('Makki', 'Makki'), ('Modecom', 'Modecom'), ('Montech', 'Montech'), ('MSI', 'MSI'), ('NZXT', 'NZXT'), ('Omega', 'Omega'), ('Phanteks', 'Phanteks'), ('Powercase', 'Powercase'), ('Razer', 'Razer'), ('Redragon', 'Redragon'), ('Seasonic', 'Seasonic'), ('Segotep', 'Segotep'), ('Sharkoon', 'Sharkoon'), ('SilverStone', 'SilverStone'), ('Spire', 'Spire'), ('Thermaltake', 'Thermaltake'), ('TrendSonic', 'TrendSonic'), ('Xigmatek', 'Xigmatek'), ('Zalman', 'Zalman')], max_length=15)),
                ('series', models.CharField(blank=True, max_length=35, null=True)),
                ('tower_size', models.CharField(blank=True, choices=[('Micro Tower', 'Micro Tower'), ('Mini Tower', 'Mini Tower'), ('Mid Tower', 'Mid Tower'), ('Full Tower', 'Full Tower'), ('Super Tower', 'Super Tower')], max_length=12, null=True)),
                ('form_factor', models.CharField(blank=True, choices=[('ATX', 'ATX'), ('E-ATX', 'E-ATX'), ('Micro-ATX', 'Micro-ATX'), ('Micro-ITX', 'Micro-ITX'), ('Mini-ATX', 'Mini-ATX'), ('Mini-DTX', 'Mini-DTX'), ('Mini-ITX', 'Mini-ITX'), ('DTX', 'DTX'), ('ITX', 'ITX'), ('XL-ATX', 'XL-ATX')], max_length=15, null=True)),
                ('width', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1000)])),
                ('height', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1000)])),
                ('depth', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1000)])),
                ('psu_max_len', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(500)])),
                ('gpu_max_len', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(500)])),
                ('front_fans', models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], default='0', max_length=2, null=True)),
                ('top_fans', models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], default='0', max_length=2, null=True)),
                ('bottom_fans', models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], default='0', max_length=2, null=True)),
                ('rear_fans', models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], default='1', max_length=2, null=True)),
                ('colour', models.CharField(blank=True, choices=[('Black', 'Black'), ('White', 'White'), ('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green'), ('Gold', 'Gold'), ('Silver', 'Silver'), ('Grey', 'Grey'), ('Pink', 'Pink')], max_length=8, null=True)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
