# Generated by Django 5.0.2 on 2024-03-19 11:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('manufacturer', models.CharField(choices=[('INTEL', 'Intel'), ('AMD', 'AMD')], max_length=5)),
                ('cpu_architecture', models.CharField(blank=True, max_length=25, null=True)),
                ('cpu_socket', models.CharField(blank=True, max_length=15, null=True)),
                ('total_cores', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('p_core_base_clock', models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0.1)])),
                ('p_core_max_clock', models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0.1)])),
                ('cpu_level_3_cache', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cpu_release_date', models.DateField(blank=True, null=True)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
