# Generated by Django 5.0.2 on 2024-03-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpu',
            old_name='p_core_max_clock',
            new_name='p_core_boost_clock',
        ),
        migrations.AlterField(
            model_name='cpu',
            name='manufacturer',
            field=models.CharField(choices=[('Intel', 'Intel'), ('AMD', 'AMD')], max_length=5),
        ),
    ]
