# Generated by Django 5.0.2 on 2024-04-07 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('case', '0001_initial'),
        ('cpu', '0002_rename_p_core_max_clock_cpu_p_core_boost_clock_and_more'),
        ('gpu', '0001_initial'),
        ('mobo', '0001_initial'),
        ('psu', '0001_initial'),
        ('ram', '0001_initial'),
        ('storage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_name', models.CharField(max_length=40, unique=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('approx_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('case_part', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='computers', to='case.case')),
                ('cpu_part', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='computers', to='cpu.cpu')),
                ('gpu_part', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='computers', to='gpu.gpu')),
                ('mobo_part', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='computers', to='mobo.mobo')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='computers', to=settings.AUTH_USER_MODEL)),
                ('psu_part', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='computers', to='psu.psu')),
                ('ram_part', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='computers', to='ram.ram')),
                ('storage_part', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='computers', to='storage.storage')),
            ],
        ),
    ]
