# Generated by Django 5.0.2 on 2024-04-05 06:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('manufacturer', models.CharField(choices=[('Asus', 'Asus'), ('ASRock', 'ASRock'), ('Biostar', 'Biostar'), ('EVGA', 'EVGA'), ('Gigabyte', 'Gigabyte'), ('MSI', 'MSI'), ('NZXT', 'NZXT')], max_length=10)),
                ('platform', models.CharField(choices=[('Intel', 'Intel'), ('AMD', 'AMD')], max_length=5)),
                ('cpu_socket', models.CharField(blank=True, max_length=15, null=True)),
                ('chipset', models.CharField(blank=True, max_length=50, null=True)),
                ('series', models.CharField(blank=True, max_length=25, null=True)),
                ('atx_factor', models.CharField(blank=True, choices=[('XL-ATX', 'XL-ATX'), ('E-ATX', 'E-ATX'), ('ATX', 'ATX'), ('Micro-ATX', 'Micro-ATX'), ('Mini-ITX', 'Mini-ITX'), ('Thin Mini-ITX', 'Thin Mini-ITX')], max_length=14, null=True)),
                ('memory_type', models.CharField(blank=True, choices=[('DDR4', 'DDR4'), ('DDR5', 'DDR5')], max_length=4, null=True)),
                ('memory_slots', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('4', '4'), ('8', '8')], max_length=1, null=True)),
                ('maximum_ram', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2048)])),
                ('gpu_interface', models.CharField(blank=True, choices=[('PCIe 2.0', 'PCIe 2.0'), ('PCIe 3.0', 'PCIe 3.0'), ('PCIe 4.0', 'PCIe 4.0'), ('PCIe 5.0', 'PCIe 5.0')], max_length=8, null=True)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
