# Generated by Django 5.0.2 on 2024-04-06 11:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('manufacturer', models.CharField(choices=[('ADATA', 'ADATA'), ('Apacer', 'Apacer'), ('Biostar', 'Biostar'), ('Corsair', 'Corsair'), ('Crucial', 'Crucial'), ('Dynac', 'Dynac'), ('G.Skill', 'G.Skill'), ('Gigabyte', 'Gigabyte'), ('HP', 'HP'), ('Kingston', 'Kingston'), ('Lexar', 'Lexar'), ('Patriot', 'Patriot'), ('Samsung', 'Samsung'), ('Silicon Power', 'Silicon Power'), ('SK Hynix', 'SK Hynix'), ('TeamGroup', 'TeamGroup'), ('Thermaltake', 'Thermaltake'), ('Transcend', 'Transcend')], max_length=15)),
                ('series', models.CharField(blank=True, max_length=35, null=True)),
                ('memory_type', models.CharField(blank=True, choices=[('DDR4', 'DDR4'), ('DDR5', 'DDR5')], max_length=5, null=True)),
                ('total_ram', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(256)])),
                ('max_frequency', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(8800)])),
                ('default_frequency', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(6600)])),
                ('cas_latency', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)])),
                ('number_of_sticks', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('4', '4'), ('8', '8')], max_length=2, null=True)),
                ('colour', models.CharField(blank=True, choices=[('Black', 'Black'), ('White', 'White'), ('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green'), ('Gold', 'Gold'), ('Silver', 'Silver'), ('Grey', 'Grey'), ('Pink', 'Pink')], max_length=8, null=True)),
                ('rgb', models.CharField(blank=True, choices=[('None', 'None'), ('RGB', 'RGB'), ('ARGB', 'ARGB')], default='None', max_length=4, null=True)),
                ('warranty', models.CharField(blank=True, max_length=25, null=True)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
