# Generated by Django 5.0.2 on 2024-04-05 19:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Psu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('manufacturer', models.CharField(choices=[('1stPlayer', '1stPlayer'), ('ADATA', 'ADATA'), ('AeroCool', 'AeroCool'), ('Antec', 'Antec'), ('Asus', 'Asus'), ('be quiet!', 'be quiet!'), ('BitFenix', 'BitFenix'), ('Chieftec', 'Chieftec'), ('Cooler Master', 'Cooler Master'), ('Corsair', 'Corsair'), ('DeepCool', 'DeepCool'), ('Delta Electronics', 'Delta Electronics'), ('Endorfy', 'Endorfy'), ('EVGA', 'EVGA'), ('Fractal Design', 'Fractal Design'), ('FSP', 'FSP'), ('Gamdias', 'Gamdias'), ('Gigabyte', 'Gigabyte'), ('InterTech', 'InterTech'), ('KEEP OUT', 'KEEP OUT'), ('Kolink', 'Kolink'), ('Lian Li', 'Lian Li'), ('Lindy', 'Lindy'), ('Makki', 'Makki'), ('MSI', 'MSI'), ('NZXT', 'NZXT'), ('Omega', 'Omega'), ('PowerColor', 'PowerColor'), ('RaptoxX', 'RaptoxX'), ('SBOX', 'SBOX'), ('Seasonic', 'Seasonic'), ('Segotep', 'Segotep'), ('Sharkoon', 'Sharkoon'), ('Spire', 'Spire'), ('Super Flower', 'Super Flower'), ('Thermaltake', 'Thermaltake'), ('TrendSonic', 'TrendSonic'), ('Xigmatek', 'Xigmatek'), ('Zalman', 'Zalman')], max_length=20)),
                ('wattage', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2050)])),
                ('form_factor', models.CharField(blank=True, choices=[('ATX', 'ATX'), ('EPS', 'EPS'), ('Flex ATX', 'Flex ATX'), ('SFX', 'SFX'), ('TFX', 'TFX')], max_length=8, null=True)),
                ('fan_size', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(360)])),
                ('plus_rating', models.CharField(blank=True, choices=[('Titanium', 'Titanium'), ('Platinum', 'Platinum'), ('Gold', 'Gold'), ('Siler', 'Silver'), ('Bronze', 'Bronze'), ('Standard (White)', 'Standard (White)')], max_length=16, null=True)),
                ('height', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(300)])),
                ('width', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(300)])),
                ('depth', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(300)])),
                ('warranty', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10)])),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
