name: Run API Tests

on:
  push:
    paths:
      - 'pc_show_off/**'
  workflow_dispatch:

jobs:
  test:
    name: Django API Tests
    runs-on: ubuntu-latest

    env:
      SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      DEBUG: ${{ secrets.DEBUG }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage

      - name: Run migrations
        run: |
          python manage.py migrate

      - name: List test files
        run: |
          find pc_show_off -name "test*.py"

      - name: Run tests with coverage
        run: |
          coverage run --source=pc_show_off manage.py test pc_show_off --verbosity=2
          coverage report
          coverage html
